# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
  migrate-database:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.2.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Verify if schema.prisma has been changed
    - uses: actions/checkout@v3
    - uses: tj-actions/verify-changed-files@v9.1
      id: verify-prisma-schema
      with:
        files: |
          ./prisma/schema.prisma
    - name: Migrate production database
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      if: contains(steps.verify-prisma-schema.outputs.changed_files, './prisma/schema.prisma')
      id: migrate-database
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      - run: npm ci
      - run: npx prisma migrate deploy


